# Generated by Django 2.1.1 on 2018-10-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=100, verbose_name='文章摘要')),
                ('imgurl', models.CharField(max_length=255, verbose_name='图片地址')),
                ('tag', models.CharField(max_length=50, verbose_name='文章标签')),
                ('top', models.BooleanField(verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='栏目名')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('ip', models.CharField(max_length=50, verbose_name='评论IP')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(verbose_name='编辑时间')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='导航栏标题')),
                ('parent', models.IntegerField(verbose_name='上一级导航栏id')),
                ('url', models.CharField(max_length=255, verbose_name='导航栏地址')),
                ('sort', models.IntegerField(default=0, verbose_name='导航栏排序')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('admin', models.BooleanField(verbose_name='是否是管理员')),
                ('image', models.CharField(max_length=255, verbose_name='用户图片')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(verbose_name='编辑时间')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.User'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Category'),
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Content'),
        ),
    ]
