# Generated by Django 2.1.1 on 2018-10-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='articles',
        ),
    ]
